### ISSUE TITLE
Stopped working - System.MissingMethodException: Method not found: 'Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCacheNotification Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.get_AfterAccess()'.

### ISSUE THREAD

**Issue by rmazanka** [hnky/VSTS-Deploy-AppSettings#11]
It was working fine, but today it has stopped working (on 2 agents, which has different update policies and weren't updated or modified since the last success release).
The errors are:

```
2019-07-16T10:04:55.8955080Z ##[error]System.MissingMethodException: Method not found: 'Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCacheNotification Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.get_AfterAccess()'.
2019-07-16T10:04:55.8966389Z    at Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache..ctor(AzureTokenCache store)
2019-07-16T10:04:55.8966783Z    at Microsoft.Azure.Commands.Common.Authentication.AzureSessionInitializer.InitializeTokenCache(IDataStore store, String cacheDirectory, String cacheFile, String autoSaveMode)
2019-07-16T10:04:55.8967090Z    at Microsoft.Azure.Commands.Common.Authentication.AzureSessionInitializer.CreateInstance(IDataStore dataStore)
2019-07-16T10:04:55.8967321Z    at Microsoft.Azure.Commands.Common.Authentication.AzureSession.Initialize(Func`1 instanceCreator, Boolean overwrite)
2019-07-16T10:04:55.8967585Z    at Microsoft.Azure.Commands.Common.Authentication.AzureSessionInitializer.InitializeAzureSession()
2019-07-16T10:04:55.8967788Z    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.OnImport()
2019-07-16T10:04:55.8968019Z    at System.Management.Automation.Runspaces.PSSnapInHelpers.ExecuteModuleInitializer(Assembly assembly, Type[] assemblyTypes, Boolean isModuleLoad)
2019-07-16T10:04:55.8968504Z    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String helpFile, Type& randomCmdletToCheckLinkDemand, Type& randomProviderToCheckLinkDemand)
2019-07-16T10:04:55.8969085Z    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
2019-07-16T10:04:55.8969473Z    at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
2019-07-16T10:04:55.8969996Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
2019-07-16T10:04:55.8970642Z    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
2019-07-16T10:04:55.8973119Z    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
2019-07-16T10:04:55.8973353Z    at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
2019-07-16T10:04:55.8973536Z    at System.Management.Automation.CommandProcessor.ProcessRecord()
2019-07-16T10:04:55.9078505Z AzurePSCmdletsVersion= 
2019-07-16T10:04:55.9078880Z 
2019-07-16T10:04:55.9079005Z 
2019-07-16T10:04:55.9304522Z ##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'AzureVersion' because it is null.
2019-07-16T10:04:55.9306328Z    at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type argumentType, Object parameterValue, Boolean recurseIntoCollections)
2019-07-16T10:04:55.9307284Z    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
2019-07-16T10:04:55.9308078Z    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
2019-07-16T10:04:55.9309344Z    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
2019-07-16T10:04:55.9310173Z    at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
2019-07-16T10:04:55.9310868Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
2019-07-16T10:04:55.9311583Z    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
2019-07-16T10:04:55.9312219Z    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
2019-07-16T10:04:55.9312865Z    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
2019-07-16T10:04:55.9313517Z    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
2019-07-16T10:04:55.9314141Z    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
2019-07-16T10:04:55.9314781Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2019-07-16T10:04:55.9315386Z --- End of stack trace from previous location where exception was thrown ---
2019-07-16T10:04:55.9315968Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2019-07-16T10:04:55.9316571Z    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
2019-07-16T10:04:55.9317431Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-07-16T10:04:55.9318275Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-07-16T10:04:55.9318945Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-07-16T10:04:55.9319605Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-07-16T10:04:55.9355150Z ##[error]System.Management.Automation.RuntimeException: The required minimum version (0.8.10.1) of the Azure Powershell Cmdlets are not installed.
```

The installed versions of modules are:
Get-Module:
Script     5.3.0      Azure
Script     5.1.2      Azure
Script     6.13.1     AzureRM
Script     6.5.0      AzureRM
Script     6.2.1      AzureRM
Script     5.7.0      AzureRM
...

```
Get-InstalledModule -Name Az -AllVersions
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.1.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets t...
2.4.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets t...
```

```
Get-InstalledModule -Name AzureRm -AllVersions
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
5.7.0                AzureRM                             PSGallery            Azure Resource Manager Module
6.13.1               AzureRM                             PSGallery            Azure Resource Manager Module
6.2.1                AzureRM                             PSGallery            Azure Resource Manager Module
6.5.0                AzureRM                             PSGallery            Azure Resource Manager Module
```

**Comment by hnky** [comment]
Hi,

I recommend moving to the Microsoft WebAppDeploymentV4 task.

In this task it is also possible to set App Settings now under "Application and Configuration Settings" 

https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureRmWebAppDeploymentV4/README.md
